<?php
/**
 * This is the block file for viewing picture upload module for Disrupt
 * @category design
 * @package pictureupload
 * @copyright Copyright (c) 2015 Disrupt Industries
 * @author Bryan Wu
 * @todo
 * 	- Lightbox
 * 	- Facebook sharing testing on test
 * 	- Facebook sharing testing on local
 * 	- Separate CSS file
 */
?>

<style type="text/css">
	.right{
		float: right;
	}
/*	.uploaded-image{
		width: 90%;
	}*/
	img{
		max-width: 100%;
		min-width: 100%;
		height: auto;
	}
</style>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_PI/sdk.js#xfbml=1&appId=809195452485029&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<?php
	$images = Mage::registry('uploaded_images');
	foreach($images as $image){
		echo "
			<div class='uploaded-image'>
				<a href='/uploaded_surfboard_images/$image[filename]' data-lightbox='$image[filename]'>
					<img src='/uploaded_surfboard_images/$image[filename]' />
				</a>
				<figcaption>$image[title]<span class='right'>$image[name]</span>
				</figcaption>
				<div class='fb-like' data-href='http://bw.disrupt.com/uploaded_surfboard_images/$image[filename]' data-layout='standard' data-action='like' data-show-faces='false' data-share='true'>
				</div>
			</div>";
	}
?>
